name: Copy File Workflow

on:
  push:
    paths:
      - 'Commitment-for-Getting-used-to-Pandas/local_getting_used_pandas.ipynb'

jobs:
  copy_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Copy File
      run: |
        # 파일이 변경되었을 때만 실행
        today=$(date +"%Y-%m-%d")
        if [ -n "$(git diff --name-only ${{ github.sha }}^ ${{ github.sha }} | grep 'Commitment-for-Getting-used-to-Pandas/local_getting_used_pandas.ipynb')" ]; then
          cp Commitment-for-Getting-used-to-Pandas/local_getting_used_pandas.ipynb Getting-used-to-Pandas
          git -C Getting-used-to-Pandas add ${today}.ipynb
          git -C Getting-used-to-Pandas commit -m "${today}업데이트"
          git -C Getting-used-to-Pandas push
        fi
