name: Copy File Workflow

on:
  push:
    paths:
      - 'Commitment-for-Getting-used-to-Pandas/local_getting_used_pandas.ipynb'

jobs:
  copy_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Commitment Repository
      uses: actions/checkout@v2
      with:
        repository: 'Commitment-for-Getting-used-to-Pandas'
        ref: ${{ github.event.before }} # or use ${{ github.sha }} if you prefer

    - name: Copy File
      run: |
        today=$(date +"%Y-%m-%d")
        cp local_getting_used_pandas.ipynb Getting-used-to-Pandas
        cd Getting-used-to-Pandas
        git add ${today}.ipynb
        git commit -m "Update local_getting_used_pandas.ipynb"
        git push origin main # or use the appropriate branch name

